apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dos-api-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/user1221510/DOS2526-E.git
    targetRevision: dev_francisco  # A sua branch de trabalho
    path: charts/products-api
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: dev-francisco
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true