# Imagem base oficial do Jenkins 
FROM jenkins/jenkins:lts

# Passa para Root para ter permissão de instalar pacotes
USER root

# 1. Instala Docker, Wget e as bibliotecas críticas do .NET
# - docker.io: Para o Jenkins falar com o Docker
# - wget: Para descarregar o instalador da Microsoft
# - libicu-dev: OBRIGATÓRIO para o .NET funcionar (Globalização)
# - libgdiplus: OBRIGATÓRIO para gerar Imagens/PDFs/Relatórios (System.Drawing)
RUN apt-get update && \
    apt-get install -y docker.io wget libicu-dev libgdiplus && \
    rm -rf /var/lib/apt/lists/*

# 2. Instalar o .NET 9.0 SDK
# Adiciona o repositório oficial da Microsoft e instala o SDK
RUN wget https://packages.microsoft.com/config/debian/12/packages-microsoft-prod.deb -O packages-microsoft-prod.deb && \
    dpkg -i packages-microsoft-prod.deb && \
    rm packages-microsoft-prod.deb && \
    apt-get update && \
    apt-get install -y dotnet-sdk-9.0

# 3. Instalar o SonarQube Scanner (Ferramenta Global .NET)
RUN dotnet tool install --global dotnet-sonarscanner

# 4. Adicionar as ferramentas .NET ao PATH para o sistema as encontrar
ENV PATH="$PATH:/root/.dotnet/tools"

# 5. Verificação das Instalações
RUN dotnet --version && docker --version