app:
  replicaCount: 1
  image:
    repository: dos2526-api
    tag: "latest"            # <--- O Jenkins vai procurar esta linha 'tag:' para mudar
    pullPolicy: IfNotPresent # <--- Mantenha 'IfNotPresent' para funcionar localmente
  service:
    type: ClusterIP
    port: 80
    targetPort: 8080
  env:
    environment: "Development"

database:
  enabled: true
  image:
    repository: mcr.microsoft.com/mssql/server
    tag: "latest"
  password: "GrupoE2526!" 
  service:
    port: 1433
  persistence:
    enabled: true
    size: 2Gi