app:
  replicaCount: 1
  image:
    repository: dos2526-api
    tag: "dev-francisco-2026-01-19-0007"
    pullPolicy: IfNotPresent
  service:
    # Mudar de ClusterIP para NodePort para expor para fora
    type: NodePort 
    port: 80
    targetPort: 8080
    # AQUI ESTÁ A CHAVE: Define a porta fixa no teu PC
    nodePort: 30050 
  env:
    environment: "Development"

database:
  enabled: true
  image:
    repository: mcr.microsoft.com/mssql/server
    tag: "latest"
  password: "GrupoE2526!" 
  service:
    port: 1433
  persistence:
    enabled: true
    size: 2Gi