apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "products-api.fullname" . }}-app
  labels:
    {{- include "products-api.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  replicas: {{ .Values.app.replicaCount }}
  selector:
    matchLabels:
      {{- include "products-api.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: api
  template:
    metadata:
      labels:
        {{- include "products-api.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: api
    spec:
      containers:
        - name: {{ .Chart.Name }}
          # Garanta que estas variáveis correspondem à estrutura do values.yaml
          image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tag }}"
          imagePullPolicy: {{ .Values.app.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.app.service.targetPort }}
              protocol: TCP
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: {{ .Values.app.env.environment }}
            - name: ConnectionStrings__DefaultConnection
              value: "Server={{ include "products-api.fullname" . }}-db;Database=master;User Id=sa;Password={{ .Values.database.password }};TrustServerCertificate=True;"