apiVersion: v1
kind: Service
metadata:
  name: {{ include "products-api.fullname" . }}-app
  labels:
    {{- include "products-api.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  # 1. Lê o tipo (NodePort) do values.yaml
  type: {{ .Values.app.service.type }}
  ports:
    - port: {{ .Values.app.service.port }}
      targetPort: {{ .Values.app.service.targetPort }}
      protocol: TCP
      name: http
      # 2. SE for NodePort, atribui a porta 30050 (ou 30055)
      {{- if eq .Values.app.service.type "NodePort" }}
      nodePort: {{ .Values.app.service.nodePort }}
      {{- end }}
  selector:
    {{- include "products-api.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api