apiVersion: v1
kind: Service
metadata:
  name: {{ include "products-api.fullname" . }}-app
  labels:
    {{- include "products-api.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  # Lê o tipo que o Jenkins definiu (NodePort)
  type: {{ .Values.app.service.type }}
  ports:
    - port: {{ .Values.app.service.port }}
      targetPort: {{ .Values.app.service.targetPort }}
      protocol: TCP
      name: http
      # Só aplica a porta 30050 se o tipo for NodePort
      {{- if eq .Values.app.service.type "NodePort" }}
      nodePort: {{ .Values.app.service.nodePort }}
      {{- end }}
  selector:
    {{- include "products-api.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api